config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :blogs
  root to: 'home#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
# frozen_string_literal: true

class Blog < ApplicationRecord
  validates :title, length: { minimum: 2 }
  validates :text,  length: { minimum: 2 }

  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :blogs, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # They are searched from right to left, from bottom to top, and up the hierarchy.
  rescue_from Exception,                      with: :render500
  rescue_from ActiveRecord::RecordNotFound,   with: :render404
  rescue_from ActionController::RoutingError, with: :render404
  before_action :authenticate_user!

  def render404
    render template: 'errors/404', status: :not_found, layout: 'application', content_type: 'text/html'
  end

  def render500
    render template: 'errors/500', status: :internal_server_error, layout: 'application',
           content_type: 'text/html'
  end
end

app/controllers/blogs_controller.rb
# frozen_string_literal: true

class BlogsController < ApplicationController
  before_action :authenticate_user!, only: %i[index new create edit update destroy]
  before_action :fetch_current_blog, only: %i[edit update destroy]

  def index
    @blogs = current_user.blogs.all
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def new
    @blog = current_user.blogs.new
  end

  def create
    @blog = current_user.blogs.new(blog_params)
    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_path(@blog), notice: 'Blog was successfully created.' }
        format.json { render json: @blog, status: :ok, notice: 'Blog was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_path(@blog), notice: 'Blog was successfully updated.' }
        format.json { render json: @blog, status: :ok, notice: 'Blog was successfully updated.' }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @blog.destroy
  end

  private

  def fetch_current_blog
    @blog = current_user.blogs.find(params[:id])
  end

  def blog_params
    params.require(:blog).permit(:title, :text)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  before_action :authenticate_user!, only: %i[index]

  def index
    @blogs = current_user.blogs.all
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/blogs_helper.rb
# frozen_string_literal: true

module BlogsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/blogs/_form.html.erb
<ul>
  <% @blog.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>

<%= form_with model: blog, local: true do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field 'title' %>
  </div>
  <div class="field">
    <%= f.label :text %>
    <%= f.text_field 'text' %>
  </div>
  <%= f.submit %><br>
<% end %>

app/views/blogs/edit.html.erb
<h1>Blogs#edit</h1>

<%= render "form", blog: @blog %>

app/views/blogs/index.html.erb
<h1>Blogs#index</h1>
<% @blogs.each do |blog| %>
  <%= link_to blog.title, blog_path(blog) %><br>
<% end %>

<%= link_to "作成", new_blog_path %>

app/views/blogs/new.html.erb
<h1>Blogs#new</h1>

<%= render "form", blog: @blog %>

app/views/blogs/show.html.erb
<h1>Blogs#show</h1>
<%= @blog.title %><br>
<%= @blog.text %><br>

<% if user_signed_in? && @blog.user == current_user %>
  <%= link_to '編集', edit_blog_path(@blog.id) %>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<% @blogs.each do |blog| %>
  <%= link_to blog.title, blog_path(blog) %><br>
<% end %>

<%= link_to "作成", new_blog_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrainingRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav>
        <% if user_signed_in? %>
        <strong><%= link_to current_user.name, blogs_path %></strong>
        <%= link_to 'プロフィール変更', edit_user_registration_path %>
        <%= link_to 'ログアウト', destroy_user_session_path %>
      <% else %>
        <%= link_to 'サインアップ', new_user_registration_path %>
        <%= link_to 'ログイン', new_user_session_path %>
        <% end %>
      </nav>
      <%= link_to 'トップ', root_path %>
      <%= link_to 'ブログ一覧', blogs_path %>
    </header>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>